// <auto-generated />
using System.Collections.Generic;
using LeoGRpcApi.Api.Persistence.Util;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ninjas.Api.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250708091132_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ninjas")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ninjas.Api.Persistence.Model.Mission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Dangerousness")
                        .HasColumnType("double precision")
                        .HasColumnName("dangerousness");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_mission");

                    b.ToTable("mission", "ninjas");
                });

            modelBuilder.Entity("Ninjas.Api.Persistence.Model.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_name");

                    b.Property<long?>("CurrentMissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_mission_id");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.PrimitiveCollection<List<string>>("SpecialSkills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("special_skills");

                    b.PrimitiveCollection<int[]>("WeaponProficiencies")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("weapon_proficiencies");

                    b.HasKey("Id")
                        .HasName("pk_ninja");

                    b.HasIndex("CurrentMissionId")
                        .HasDatabaseName("ix_ninja_current_mission_id");

                    b.ToTable("ninja", "ninjas");
                });

            modelBuilder.Entity("Ninjas.Api.Persistence.Model.Ninja", b =>
                {
                    b.HasOne("Ninjas.Api.Persistence.Model.Mission", "CurrentMission")
                        .WithMany("AssignedNinjas")
                        .HasForeignKey("CurrentMissionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ninja_mission_current_mission_id");

                    b.Navigation("CurrentMission");
                });

            modelBuilder.Entity("Ninjas.Api.Persistence.Model.Mission", b =>
                {
                    b.Navigation("AssignedNinjas");
                });
#pragma warning restore 612, 618
        }
    }
}
